build:
  command: npm run build
  publish: dist/stadium-map/browser

# Redirect all requests (including deep links) to index.html for SPA routing
redirects:
  - from: /*
    to: /index.html
    status: 200
