#!/usr/bin/env sh
# Generates src/app/config/app.config.local.ts from Netlify environment variables.
# Safe to run in CI or locally. Uses empty strings when variables are not set.

set -e

OUT_FILE="src/app/config/app.config.local.ts"
mkdir -p "$(dirname "$OUT_FILE")"

# Helper to escape single quotes for safe insertion into single-quoted JS strings
esc() {
  printf "%s" "$1" | sed "s/'/'\\''/g"
}

YMAP_KEY="$(esc "${NETLIFY_YANDEX_MAPS_API_KEY:-}" )"
# Do NOT include default credentials here — require environment variables.
# If env vars are not provided, write empty strings so secrets won't appear.
AUTH_USER="$(esc "${NETLIFY_AUTH_USERNAME:-}" )"
AUTH_PASS="$(esc "${NETLIFY_AUTH_PASSWORD:-}" )"

cat > "$OUT_FILE" <<EOF
// Auto-generated by netlify-generate-config.sh from Netlify environment variables.
// Do not commit this file if it contains secrets; it is generated at build time.

export const appConfigLocal = {
  yandexMapsApiKey: '${YMAP_KEY}',
  authUsername: '${AUTH_USER}',
  authPassword: '${AUTH_PASS}'
};

export type AppConfigLocal = typeof appConfigLocal;
EOF

# Make the generated file readable
chmod 644 "$OUT_FILE"

echo "Generated $OUT_FILE from environment variables."
