#!/usr/bin/env sh
# Generates src/app/config/app.config.local.ts from Netlify environment variables.
# Safe to run in CI or locally. Uses empty strings when variables are not set.

set -e

OUT_FILE="src/app/config/app.config.local.ts"
mkdir -p "$(dirname "$OUT_FILE")"

# Helper to escape single quotes for safe insertion into single-quoted JS strings
esc() {
  printf "%s" "$1" | sed "s/'/'\\''/g"
}

# SECURITY: do NOT emit sensitive values into client bundles during CI.
# Even if Netlify env vars are set, we will NOT write auth credentials or
# private keys into the generated client config file. This prevents the
# build output from containing secrets that Netlify will flag.
YMAP_KEY=""
AUTH_USER=""
AUTH_PASS=""

cat > "$OUT_FILE" <<EOF
// Auto-generated by netlify-generate-config.sh from Netlify environment variables.
// Do not commit this file if it contains secrets; it is generated at build time.

export const appConfigLocal = {
  yandexMapsApiKey: '${YMAP_KEY}',
  authUsername: '${AUTH_USER}',
  authPassword: '${AUTH_PASS}'
};

export type AppConfigLocal = typeof appConfigLocal;
EOF

# Make the generated file readable
chmod 644 "$OUT_FILE"

echo "Generated $OUT_FILE from environment variables."
